/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.15
 * Generated at: 2023-11-22 10:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("		/* Styles for container and halves */\r\n");
      out.write("		\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Arial', sans-serif;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    background-color: #f5f5f5;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("    color: rgb(34, 29, 29);\r\n");
      out.write("    text-shadow: 1px 1px rgb(255, 3, 209);\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("input[type=\"text\"],\r\n");
      out.write("input[type=\"number\"],\r\n");
      out.write("button {\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style for submit buttons */\r\n");
      out.write("button[type=\"submit\"] {\r\n");
      out.write("  background-color: #4caf50;\r\n");
      out.write("  color: white;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Hover effect for buttons */\r\n");
      out.write("button[type=\"submit\"]:hover {\r\n");
      out.write("  background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  background-color: #E5C9C7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  background-color: #E5C9C7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".halfleft {\r\n");
      out.write("  left: 0;\r\n");
      out.write("  backgrond-color: 	#F2D6D6;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border-style: solid;\r\n");
      out.write("  border: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".upperleft {\r\n");
      out.write("  left: 0;\r\n");
      out.write("  backgrond-color: 	#F2D6D6;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border-style: solid;\r\n");
      out.write("  border: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".halfright {\r\n");
      out.write("  right: 0;\r\n");
      out.write("  background-color: #F2D6D6;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border-style: solid;\r\n");
      out.write("  border: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".upperright {\r\n");
      out.write("  right: 0;\r\n");
      out.write("  background-color: #F2D6D6;\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border-style: solid;\r\n");
      out.write("  border: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Styles for form inputs and labels */\r\n");
      out.write("/* ... (use the styles provided in the previous CSS example) */\r\n");
      out.write("		\r\n");
      out.write(".container text {\r\n");
      out.write("    /* width: 100px; */\r\n");
      out.write("    width: 440px;\r\n");
      out.write("    height: 450px;\r\n");
      out.write("    /* border: #4caf50;*/\r\n");
      out.write("/*     border-style: inherit;  */\r\n");
      out.write("	  position: absolute;\r\n");
      out.write("	  background-color: #f7f7f7;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("    background-color: #333;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script >function redirectToPage5() {\r\n");
      out.write("    // Use the window.location.href property to set the URL you want to redirect to.\r\n");
      out.write("    window.location.href = 'viewtransection.jsp';\r\n");
      out.write("    //document.getElementById(\"logoutForm\").submit();\r\n");
      out.write("}\r\n");
      out.write("function redirectToPage() {\r\n");
      out.write("    // Use the window.location.href property to set the URL you want to redirect to.\r\n");
      out.write("    window.location.href = 'viewfeedback.jsp';\r\n");
      out.write("    //document.getElementById(\"logoutForm\").submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("	<div class=\"logo\">CARDX</div>\r\n");
      out.write("	</header>\r\n");
      out.write("<div class=\"top\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"upperleft\">\r\n");
      out.write("	\r\n");
      out.write("		<h3 align=\"center\">View all type Transection table here</h3>\r\n");
      out.write("		<h3 align=\"center\">  <button type=\"submit\" onclick=\"redirectToPage5()\">View Transections</button></h3>\r\n");
      out.write("	<h3 align=\"center\">View all Feedbacks</h3>\r\n");
      out.write("		<h3 align=\"center\"><button type=\"submit\" onclick=\"redirectToPage()\">View Feedbacks</button></h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"upperright\">\r\n");
      out.write("	<form method=\"post\" action=\"make_admin\">\r\n");
      out.write("	<h3 align=\"center\">Make Admin</h3>\r\n");
      out.write("		<label for=\"newadmin\">Email id:</label>\r\n");
      out.write("		<input type=\"text\" id=\"newadmin\" name=\"newadmin\"><br>\r\n");
      out.write("		\r\n");
      out.write("		<h3 align=\"center\"><button type=\"submit\">Give access</button></h3>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	<div class=\"halfleft\">\r\n");
      out.write("	<form method=\"post\" action=\"add-newcar\" onsubmit=\"return validateForm()\">\r\n");
      out.write("	<h3 align=\"center\">Add New car</h3>\r\n");
      out.write("		<label for=\"Model\">Model:</label>\r\n");
      out.write("		<input type=\"text\" id=\"Model\" name=\"Model\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"company\">Company:</label>\r\n");
      out.write("		<input type=\"text\" id=\"company\" name=\"company\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"Price\">Price:</label>\r\n");
      out.write("		<input type=\"text\" id=\"Price\" name=\"Price\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"colour\">Colour:</label>\r\n");
      out.write("		<input type=\"text\" id=\"colour\" name=\"colour\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"fuel\">Fuel type:</label>\r\n");
      out.write("		<input type=\"text\" id=\"fuel\" name=\"fuel\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"safety\">Safety Ratings:</label>\r\n");
      out.write("		<input type=\"number\" id=\"safety\" name=\"safety\" min=\"0\" max=\"5\" step=\"0.1\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"transmission\">Transmission type:</label>\r\n");
      out.write("		<input type=\"text\" id=\"tranmission\" name=\"transmission\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"warranty\">Warranty_year:</label>\r\n");
      out.write("		<input type=\"text\" id=\"warranty\" name=\"warranty\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<h3 align=\"center\"><button type=\"submit\">Add car</button></h3>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"halfright\">\r\n");
      out.write("	<form method=\"post\" action=\"add-rentcar\" onsubmit=\"return validateForm()\">\r\n");
      out.write("	\r\n");
      out.write("	<h3 align=\"center\">Add Rental car</h3>\r\n");
      out.write("		<label for=\"Model\">Model:</label>\r\n");
      out.write("		<input type=\"text\" id=\"Model\" name=\"Model\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"company\">Company:</label>\r\n");
      out.write("		<input type=\"text\" id=\"company\" name=\"company\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"Price\">Price per day:</label>\r\n");
      out.write("		<input type=\"text\" id=\"Price\" name=\"Price\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"colour\">Colour:</label>\r\n");
      out.write("		<input type=\"text\" id=\"colour\" name=\"colour\" required><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<label for=\"fuel\">Fuel type:</label>\r\n");
      out.write("		<input type=\"text\" id=\"fuel\" name=\"fuel\" required><br><br>\r\n");
      out.write("	\r\n");
      out.write("		<h3 align=\"center\"><button type=\"submit\">Add car</button></h3>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
